### PR TITLE
Fix HTTParty parsed_response to allow updates

### PR DESCRIPTION
**Pull request by alexQueue**
This is a duplicate of https://github.com/jazminschroeder/fedex/pull/124 but I incorporated @jaysonvirissimo's comment so that we can make progress on this.

We'd love to use this update without having to fork this gem.

### CODE REVIEW

**Comment by nathanbertram** [comment]
Have the same issue here - 👍  for this fix

**Comment by Superpencil** [comment]
Thanks @jazminschroeder plz pull

**Comment by Superpencil** [comment]
I understand you want to do a major refactor @jazminschroeder, but your stuff is used in the real world, and currently this is blocking upgrading from `ruby 2.3` to `ruby 2.4`, so it would be good to get this one in just for basic support.

**Comment by boie0025** [comment]
👍

**Comment by PascalPixel** [comment]
Thank you @jazminschroeder !!!

**Pull request merged**
